### ISSUE TITLE
Set up a structure for the repo

### ISSUE THREAD

**Issue by Anupam-dagar** [opencodeiiita/GirlsDoCode#10]
The template structure is not so proper. A proper structure makes it easy to find the files and code.
Suggested actions:
1. Create a static folder at the root with `css`,`js` and `img` folder inside it.
2. All the `js`,`css` and `img` should be moved to their respective folders.
3. `index.html` stays in the root of the repository.
4. Remove `gulp.js`, `package.json` and `package-lock.json`.

### Please note that changing folder names and file path might break their import in the html file, make sure to fix those also in the PR.

**Comment by niftyy** [comment]
@opencodebot claim

**Comment by Anupam-dagar** [comment]
@nifty accept the invite for being an outside collaborator. After that you can claim any of the issues on this repo directly using the bot.

**Comment by Anupam-dagar** [comment]
@niftyy this repo is only for girls to contribute. Please head over to other repos.

**Comment by Archies11** [comment]
@opencodebot claim

**Comment by Jahanvi21** [comment]
@opencodebot claim
